# Generated by Django 3.2.5 on 2021-10-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
