# Generated by Django 3.2.6 on 2021-09-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderItems',
            new_name='CartOrderItem',
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'Product Attributes'},
        ),
    ]
