# Generated by Django 3.2.6 on 2021-09-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210901_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItem',
        ),
    ]
