# Generated by Django 3.2.6 on 2021-08-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='color_code',
            new_name='color',
        ),
    ]
