# Generated by Django 3.2.6 on 2021-08-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210824_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='departement',
            new_name='category',
        ),
    ]
