# Generated by Django 3.1.6 on 2021-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_smallpub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallpub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
