# Generated by Django 3.1.6 on 2021-10-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_viewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewer',
            old_name='viewer',
            new_name='count',
        ),
    ]
