# Generated by Django 3.1.6 on 2021-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211004_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
